[tool.poetry]
name = "sunflower"
version = "0.1.0"
description = ""
authors = ["Julien Beisel"]

[tool.poetry.dependencies]
python = "^3.7"
black = "^19.10b0"

[tool.poetry.dev-dependencies]
pytest = "^3.4"